on:
  issue_comment:
    types: [created]

jobs:
  fact-check:
    runs-on: ubuntu-latest
    name: "Verify statements in content diff for truthness"
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/testcheck')
    steps:
      - uses: actions/checkout@v3

      - name: Cache Python
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install package
        run: pipx install poetry && poetry install --no-interaction

      - name: Run script
        run: |
          poetry run article-check \
            --pull-url "${{ github.event.issue.pull_request.url }}" \
            --github-token "${{ secrets.TOKEN }}" \
            --wp-key "${{ secrets.WP_KEY }}" 
