on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  fact-check:
    runs-on: ubuntu-latest
    name: "Verify statements in content diff for truthness"
    needs: [ permission-check-job ]
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/factcheck')    
    steps:
      - uses: actions/checkout@v3

      - name: Cache Python
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install package
        run: pipx install poetry && poetry install --no-interaction

      - name: Run script
        run: |
          poetry run article-check \
            --pull-url "${{ github.event.issue.pull_request.url }}" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --api-key "${{ secrets.LLM_API_KEY }}"  \
            --search-api-key "${{ secrets.SEARCH_API_KEY }}"
