on:
  issue_comment:
    types: [created]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment contains /formatcheck
        id: check-comment
        run: |
          if [[ ${{ github.event.comment.body }} == *"/formatcheck"* ]]; then
            echo "Comment contains /formatcheck"
            echo "::set-output name=run-check::true"
          else
            echo "Comment does not contain /formatcheck"
            echo "::set-output name=run-check::false"
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install --no-interaction

      - name: Run format check
        if: steps.check-comment.outputs.run-check == 'true'
        run: |
          poetry run format-check \
            --pull-url "${{ github.event.issue.pull_request.url }}" \
            --github-token "${{ secrets.TOKEN }}" \
            --openai-key "${{ secrets.OPENAI_KEY }}" \
            --content-path "content"
